package com.zerodsoft.scheduleweather.navermap;

public enum MarkerType {
	SEARCH_RESULT,
	SEARCH_RESULT_ADDRESS,
	SEARCH_RESULT_PLACE,
	BUILDING,
	RESTAURANT,
	SELECTED_PLACE_CATEGORY,
	COORD_TO_ADDRESS,
	SELECTED_ADDRESS_IN_EVENT,
	SELECTED_PLACE_IN_EVENT,
	FAVORITE,
	LONG_CLICKED_MAP,
	CRITERIA_LOCATION_FOR_RESTAURANTS
}